### ISSUE TITLE
請問apex.py中要更改什麽數據嗎

### ISSUE THREAD

**Issue by zhouhangshuhai** [gcobs051094/Apex_YOLOv5#5]

**Comment by gcobs051094** [comment]
環境架設好，直接運行.py。
若執行成功，會有一個小視窗可以看見偵測結果。

**Comment by zhouhangshuhai** [comment]
好吧 我執行後只有一個運行成功的窗口，並沒有顯示偵測視窗，我的環境什麼的也應該是搭建好的，執行過程中並沒有報錯誤

**Comment by gcobs051094** [comment]
apex.py 有個參數--show-window 設成true
